# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Control_0_0/design_1_Control_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Control_0_0 || ORIG_REF_NAME==design_1_Control_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_2 || ORIG_REF_NAME==design_1_axi_gpio_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_3 || ORIG_REF_NAME==design_1_axi_gpio_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_4 || ORIG_REF_NAME==design_1_axi_gpio_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_y_input_0/design_1_axi_gpio_y_input_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_y_input_0 || ORIG_REF_NAME==design_1_axi_gpio_y_input_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_rst_0/design_1_axi_gpio_rst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_rst_0 || ORIG_REF_NAME==design_1_axi_gpio_rst_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_done_per_0/design_1_axi_gpio_done_per_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_done_per_0 || ORIG_REF_NAME==design_1_axi_gpio_done_per_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_done_per_1/design_1_axi_gpio_done_per_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_done_per_1 || ORIG_REF_NAME==design_1_axi_gpio_done_per_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_delta_done_0/design_1_axi_gpio_delta_done_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_delta_done_0 || ORIG_REF_NAME==design_1_axi_gpio_delta_done_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_delta_done_1/design_1_axi_gpio_delta_done_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_delta_done_1 || ORIG_REF_NAME==design_1_axi_gpio_delta_done_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_5/design_1_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_5 || ORIG_REF_NAME==design_1_axi_gpio_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_6 || ORIG_REF_NAME==design_1_axi_gpio_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_7/design_1_axi_gpio_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_7 || ORIG_REF_NAME==design_1_axi_gpio_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_8/design_1_axi_gpio_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_8 || ORIG_REF_NAME==design_1_axi_gpio_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_sel_corrected_w_0/design_1_axi_gpio_sel_corrected_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_sel_corrected_w_0 || ORIG_REF_NAME==design_1_axi_gpio_sel_corrected_w_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_rst_1/design_1_axi_gpio_rst_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_rst_1 || ORIG_REF_NAME==design_1_axi_gpio_rst_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_update_w_0/design_1_axi_gpio_update_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_update_w_0 || ORIG_REF_NAME==design_1_axi_gpio_update_w_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_update_w_1/design_1_axi_gpio_update_w_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_update_w_1 || ORIG_REF_NAME==design_1_axi_gpio_update_w_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_0_0/design_1_tier2_xbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_0_0 || ORIG_REF_NAME==design_1_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_1_0/design_1_tier2_xbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_1_0 || ORIG_REF_NAME==design_1_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_2_0/design_1_tier2_xbar_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_2_0 || ORIG_REF_NAME==design_1_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: d:/Facultate/AN3/Sem1/SSC/Proiect/Perceptron-FPGA_delta_perceptron/Perceptron-FPGA_delta_perceptron/Perceptron-FPGA/Perceptron.gen/sources_1/bd/design_1/design_1_ooc.xdc
